### ISSUE TITLE
AfterEffect入門 結婚式用動画作成

### ISSUE THREAD

**Issue by keitakawamoto** [keitakawamoto/orangebomb.org#31]
依頼があり、作品ドリブン学習にもってこいなのでやる。
基本操作・イラスト系の操作マスターは https://github.com/keitakawamoto/orangebomb.org/issues/8

## 要件

やっていく途中で、AfterEffectは 映像素材作成ツール 、映像制作ツールは Adobe Premiereであると知った。よってpremiereでやった部分はpremiereのissueへリンクを貼る。

- [x] 字幕を入れる https://github.com/keitakawamoto/orangebomb.org/issues/8#issuecomment-216662287 （Adobe Premiere https://github.com/keitakawamoto/orangebomb.org/issues/36 ）
- [x] 音楽を重ねる（Adobe Premiere https://github.com/keitakawamoto/orangebomb.org/issues/36#issuecomment-219196639 ）
- [x] 音楽の音量を部分的に操作する（Adobe Premiere https://github.com/keitakawamoto/orangebomb.org/issues/36#issuecomment-219196639 ）
- [x] カット編集 （AfterEffectのカット編集もできた。Adobe Premiere のほうは https://github.com/keitakawamoto/orangebomb.org/issues/36 ）
- [x] カットごとに別々の動画ファイルを配置する（Adobe Premiere https://github.com/keitakawamoto/orangebomb.org/issues/36 ）
- [x] 写真と動画、どちらも利用する（Adobe Premiere https://github.com/keitakawamoto/orangebomb.org/issues/36 ）
- [x] 曲に合わせた多少のタイミング調整
- [x] 終わりの部分の `Happy Wedding` 表記登場の際のエフェクト追加・調整
- [x] 動画素材の向きがおかしい場合回転させる

上記は全て本番用映像ではなく、テスト用サンプル素材を利用する。

**Comment by keitakawamoto** [comment]
## カット編集

参考：https://www.youtube.com/watch?v=dgula5N300M

### レイヤーを分割

まずは切りたいところでストップ。

![image](https://cloud.githubusercontent.com/assets/1661325/15097057/1477c39a-154b-11e6-87bc-33b07cbc9efd.png)

その後 `編集` > `レイヤーを分割` をすると、止めたところを軸に前後でレイヤーを分けることができる。

![image](https://cloud.githubusercontent.com/assets/1661325/15097068/605f1b5a-154b-11e6-8330-5d67453b1942.png)
![image](https://cloud.githubusercontent.com/assets/1661325/15097071/6fca3610-154b-11e6-920b-fa5cda1abf97.png)

## ワークエリアのリフト

ワークエリア（青で囲まれた部分）を調整し、`編集` > `ワークエリアのリフト` をすると、ワークエリアに囲まれた部分が空白になる。

![image](https://cloud.githubusercontent.com/assets/1661325/15097090/190d601c-154c-11e6-8714-185bcdbf2364.png)
![image](https://cloud.githubusercontent.com/assets/1661325/15097121/b78d6d22-154c-11e6-99d5-ae79c048d3e1.png)

## ワークエリアの抽出

ワークエリアを調整し、`編集` > `ワークエリアの抽出` をすると、ワークエリアに囲まれた部分がカットされ、その分後の部分が詰められ、前に来る。

![image](https://cloud.githubusercontent.com/assets/1661325/15097196/ef04f9b2-154e-11e6-80f0-e76d2786ed3d.png)

**Comment by keitakawamoto** [comment]
## レイヤーの削除

レイヤーを選択し `delete` キーで削除できる。

**Comment by keitakawamoto** [comment]
## 動画素材の回転 （AfterEffectではなくQuickTime）

QuickTime に動画を読み込ませ、 `編集` > `半時計回りに回転` などで回転させられる。
書き出しを行えばそのまま保存される。

**Comment by keitakawamoto** [comment]
動画は無事に完成した。
